// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: nft/blind_box_stage.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlindBoxStage 盲盒阶段
type BlindBoxStage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlindBoxId uint64 `protobuf:"varint,1,opt,name=blind_box_id,json=blindBoxId,proto3" json:"blind_box_id"`
	Type       uint64 `protobuf:"varint,2,opt,name=type,proto3" json:"type"`
	StartAt    string `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at"`
	EndAt      string `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at"`
	StartTime  string `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time"`
	EndTime    string `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time"`
	Limit      uint64 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit"`
	CreatedAt  string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt  string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
}

func (x *BlindBoxStage) Reset() {
	*x = BlindBoxStage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_stage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxStage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxStage) ProtoMessage() {}

func (x *BlindBoxStage) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_stage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxStage.ProtoReflect.Descriptor instead.
func (*BlindBoxStage) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_stage_proto_rawDescGZIP(), []int{0}
}

func (x *BlindBoxStage) GetBlindBoxId() uint64 {
	if x != nil {
		return x.BlindBoxId
	}
	return 0
}

func (x *BlindBoxStage) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BlindBoxStage) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *BlindBoxStage) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *BlindBoxStage) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *BlindBoxStage) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *BlindBoxStage) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *BlindBoxStage) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BlindBoxStage) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// BlindBoxStagePost Info 参数
type BlindBoxStagePost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlindBoxId uint64 `protobuf:"varint,1,opt,name=blind_box_id,json=blindBoxId,proto3" json:"blind_box_id"`
	Type       uint64 `protobuf:"varint,2,opt,name=type,proto3" json:"type"`
}

func (x *BlindBoxStagePost) Reset() {
	*x = BlindBoxStagePost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_stage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxStagePost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxStagePost) ProtoMessage() {}

func (x *BlindBoxStagePost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_stage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxStagePost.ProtoReflect.Descriptor instead.
func (*BlindBoxStagePost) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_stage_proto_rawDescGZIP(), []int{1}
}

func (x *BlindBoxStagePost) GetBlindBoxId() uint64 {
	if x != nil {
		return x.BlindBoxId
	}
	return 0
}

func (x *BlindBoxStagePost) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

// ModifyBlindBoxStagePost 创建 / 更新 阶段
type ModifyBlindBoxStagePost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlindBoxId uint64 `protobuf:"varint,1,opt,name=blind_box_id,json=blindBoxId,proto3" json:"blind_box_id"`
	Type       uint64 `protobuf:"varint,2,opt,name=type,proto3" json:"type"`
	StartAt    string `protobuf:"bytes,3,opt,name=start_at,json=startAt,proto3" json:"start_at"`
	EndAt      string `protobuf:"bytes,4,opt,name=end_at,json=endAt,proto3" json:"end_at"`
	Limit      uint64 `protobuf:"varint,5,opt,name=limit,proto3" json:"limit"`
}

func (x *ModifyBlindBoxStagePost) Reset() {
	*x = ModifyBlindBoxStagePost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_stage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyBlindBoxStagePost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyBlindBoxStagePost) ProtoMessage() {}

func (x *ModifyBlindBoxStagePost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_stage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyBlindBoxStagePost.ProtoReflect.Descriptor instead.
func (*ModifyBlindBoxStagePost) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_stage_proto_rawDescGZIP(), []int{2}
}

func (x *ModifyBlindBoxStagePost) GetBlindBoxId() uint64 {
	if x != nil {
		return x.BlindBoxId
	}
	return 0
}

func (x *ModifyBlindBoxStagePost) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *ModifyBlindBoxStagePost) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *ModifyBlindBoxStagePost) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *ModifyBlindBoxStagePost) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// BlindBoxStageResponse 返回 信息
type BlindBoxStageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string         `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *BlindBoxStage `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *BlindBoxStageResponse) Reset() {
	*x = BlindBoxStageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_stage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxStageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxStageResponse) ProtoMessage() {}

func (x *BlindBoxStageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_stage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxStageResponse.ProtoReflect.Descriptor instead.
func (*BlindBoxStageResponse) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_stage_proto_rawDescGZIP(), []int{3}
}

func (x *BlindBoxStageResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlindBoxStageResponse) GetData() *BlindBoxStage {
	if x != nil {
		return x.Data
	}
	return nil
}

// BlindBoxStagesResponse 返回列表
type BlindBoxStagesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string           `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    []*BlindBoxStage `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
}

func (x *BlindBoxStagesResponse) Reset() {
	*x = BlindBoxStagesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_stage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxStagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxStagesResponse) ProtoMessage() {}

func (x *BlindBoxStagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_stage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxStagesResponse.ProtoReflect.Descriptor instead.
func (*BlindBoxStagesResponse) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_stage_proto_rawDescGZIP(), []int{4}
}

func (x *BlindBoxStagesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlindBoxStagesResponse) GetData() []*BlindBoxStage {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_nft_blind_box_stage_proto protoreflect.FileDescriptor

var file_nft_blind_box_stage_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6e, 0x66, 0x74, 0x2f, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x78, 0x5f,
	0x73, 0x74, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6e, 0x66, 0x74,
	0x22, 0x85, 0x02, 0x0a, 0x0d, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x78, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x42,
	0x6f, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x6e, 0x64,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x49, 0x0a, 0x11, 0x42, 0x6c, 0x69, 0x6e,
	0x64, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x20, 0x0a,
	0x0c, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x17, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x42, 0x6c,
	0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x67, 0x65, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0c, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74,
	0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x59, 0x0a,
	0x15, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61,
	0x67, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5a, 0x0a, 0x16, 0x42, 0x6c, 0x69, 0x6e,
	0x64, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x67, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x26, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6e, 0x66, 0x74,
	0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x53, 0x74, 0x61, 0x67, 0x65, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nft_blind_box_stage_proto_rawDescOnce sync.Once
	file_nft_blind_box_stage_proto_rawDescData = file_nft_blind_box_stage_proto_rawDesc
)

func file_nft_blind_box_stage_proto_rawDescGZIP() []byte {
	file_nft_blind_box_stage_proto_rawDescOnce.Do(func() {
		file_nft_blind_box_stage_proto_rawDescData = protoimpl.X.CompressGZIP(file_nft_blind_box_stage_proto_rawDescData)
	})
	return file_nft_blind_box_stage_proto_rawDescData
}

var file_nft_blind_box_stage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_nft_blind_box_stage_proto_goTypes = []interface{}{
	(*BlindBoxStage)(nil),           // 0: nft.BlindBoxStage
	(*BlindBoxStagePost)(nil),       // 1: nft.BlindBoxStagePost
	(*ModifyBlindBoxStagePost)(nil), // 2: nft.ModifyBlindBoxStagePost
	(*BlindBoxStageResponse)(nil),   // 3: nft.BlindBoxStageResponse
	(*BlindBoxStagesResponse)(nil),  // 4: nft.BlindBoxStagesResponse
}
var file_nft_blind_box_stage_proto_depIdxs = []int32{
	0, // 0: nft.BlindBoxStageResponse.data:type_name -> nft.BlindBoxStage
	0, // 1: nft.BlindBoxStagesResponse.data:type_name -> nft.BlindBoxStage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_nft_blind_box_stage_proto_init() }
func file_nft_blind_box_stage_proto_init() {
	if File_nft_blind_box_stage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nft_blind_box_stage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxStage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_stage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxStagePost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_stage_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModifyBlindBoxStagePost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_stage_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxStageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_stage_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxStagesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nft_blind_box_stage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nft_blind_box_stage_proto_goTypes,
		DependencyIndexes: file_nft_blind_box_stage_proto_depIdxs,
		MessageInfos:      file_nft_blind_box_stage_proto_msgTypes,
	}.Build()
	File_nft_blind_box_stage_proto = out.File
	file_nft_blind_box_stage_proto_rawDesc = nil
	file_nft_blind_box_stage_proto_goTypes = nil
	file_nft_blind_box_stage_proto_depIdxs = nil
}
