// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: nft/blind_box.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlindBox 盲盒
type BlindBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title       string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	SubTitle    string  `protobuf:"bytes,3,opt,name=sub_title,json=subTitle,proto3" json:"sub_title"`
	Description string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	Cover       string  `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover"`
	Series      string  `protobuf:"bytes,6,opt,name=series,proto3" json:"series"`
	Price       float32 `protobuf:"fixed32,7,opt,name=price,proto3" json:"price"`
	Decimal     uint64  `protobuf:"varint,8,opt,name=decimal,proto3" json:"decimal"`
	StartAt     string  `protobuf:"bytes,9,opt,name=start_at,json=startAt,proto3" json:"start_at"`
	EndAt       string  `protobuf:"bytes,10,opt,name=end_at,json=endAt,proto3" json:"end_at"`
	Top         bool    `protobuf:"varint,11,opt,name=top,proto3" json:"top"`
	Status      uint64  `protobuf:"varint,12,opt,name=status,proto3" json:"status"`
	CreatedAt   string  `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt   string  `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
}

func (x *BlindBox) Reset() {
	*x = BlindBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBox) ProtoMessage() {}

func (x *BlindBox) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBox.ProtoReflect.Descriptor instead.
func (*BlindBox) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{0}
}

func (x *BlindBox) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlindBox) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BlindBox) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *BlindBox) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BlindBox) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *BlindBox) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *BlindBox) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BlindBox) GetDecimal() uint64 {
	if x != nil {
		return x.Decimal
	}
	return 0
}

func (x *BlindBox) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *BlindBox) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *BlindBox) GetTop() bool {
	if x != nil {
		return x.Top
	}
	return false
}

func (x *BlindBox) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BlindBox) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BlindBox) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// BlindBoxContent 盲盒内容
type BlindBoxContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlindBoxId  uint64 `protobuf:"varint,1,opt,name=blind_box_id,json=blindBoxId,proto3" json:"blind_box_id"`
	WorkId      uint64 `protobuf:"varint,2,opt,name=work_id,json=workId,proto3" json:"work_id"`
	Rarity      uint64 `protobuf:"varint,3,opt,name=rarity,proto3" json:"rarity"`
	Probability uint64 `protobuf:"varint,4,opt,name=probability,proto3" json:"probability"`
	Total       uint64 `protobuf:"varint,5,opt,name=total,proto3" json:"total"`
	Remain      uint64 `protobuf:"varint,6,opt,name=remain,proto3" json:"remain"`
	Status      uint64 `protobuf:"varint,7,opt,name=status,proto3" json:"status"`
	CreatedAt   string `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt   string `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
}

func (x *BlindBoxContent) Reset() {
	*x = BlindBoxContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxContent) ProtoMessage() {}

func (x *BlindBoxContent) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxContent.ProtoReflect.Descriptor instead.
func (*BlindBoxContent) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{1}
}

func (x *BlindBoxContent) GetBlindBoxId() uint64 {
	if x != nil {
		return x.BlindBoxId
	}
	return 0
}

func (x *BlindBoxContent) GetWorkId() uint64 {
	if x != nil {
		return x.WorkId
	}
	return 0
}

func (x *BlindBoxContent) GetRarity() uint64 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *BlindBoxContent) GetProbability() uint64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *BlindBoxContent) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BlindBoxContent) GetRemain() uint64 {
	if x != nil {
		return x.Remain
	}
	return 0
}

func (x *BlindBoxContent) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *BlindBoxContent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BlindBoxContent) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// BlindBoxIntroduction 盲盒介绍
type BlindBoxIntroduction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlindBoxId uint64 `protobuf:"varint,1,opt,name=blind_box_id,json=blindBoxId,proto3" json:"blind_box_id"`
	Content    string `protobuf:"bytes,2,opt,name=content,proto3" json:"content"`
	CreatedAt  string `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt  string `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
}

func (x *BlindBoxIntroduction) Reset() {
	*x = BlindBoxIntroduction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxIntroduction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxIntroduction) ProtoMessage() {}

func (x *BlindBoxIntroduction) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxIntroduction.ProtoReflect.Descriptor instead.
func (*BlindBoxIntroduction) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{2}
}

func (x *BlindBoxIntroduction) GetBlindBoxId() uint64 {
	if x != nil {
		return x.BlindBoxId
	}
	return 0
}

func (x *BlindBoxIntroduction) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BlindBoxIntroduction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BlindBoxIntroduction) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// SimpleBlindBox 前端 盲盒数据
type SimpleBlindBox struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Title        string  `protobuf:"bytes,2,opt,name=title,proto3" json:"title"`
	SubTitle     string  `protobuf:"bytes,3,opt,name=sub_title,json=subTitle,proto3" json:"sub_title"`
	Description  string  `protobuf:"bytes,4,opt,name=description,proto3" json:"description"`
	Introduction string  `protobuf:"bytes,5,opt,name=introduction,proto3" json:"introduction"`
	Cover        string  `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover"`
	Background   string  `protobuf:"bytes,7,opt,name=background,proto3" json:"background"`
	Series       string  `protobuf:"bytes,8,opt,name=series,proto3" json:"series"`
	Price        float32 `protobuf:"fixed32,9,opt,name=price,proto3" json:"price"`
	StartAt      uint64  `protobuf:"varint,10,opt,name=start_at,json=startAt,proto3" json:"start_at"`
	EndAt        uint64  `protobuf:"varint,11,opt,name=end_at,json=endAt,proto3" json:"end_at"`
	Open         bool    `protobuf:"varint,12,opt,name=open,proto3" json:"open"`
	Total        uint64  `protobuf:"varint,13,opt,name=total,proto3" json:"total"`
	Remain       uint64  `protobuf:"varint,14,opt,name=remain,proto3" json:"remain"`
	Contract     string  `protobuf:"bytes,15,opt,name=contract,proto3" json:"contract"`
}

func (x *SimpleBlindBox) Reset() {
	*x = SimpleBlindBox{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleBlindBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleBlindBox) ProtoMessage() {}

func (x *SimpleBlindBox) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleBlindBox.ProtoReflect.Descriptor instead.
func (*SimpleBlindBox) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{3}
}

func (x *SimpleBlindBox) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SimpleBlindBox) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SimpleBlindBox) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *SimpleBlindBox) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SimpleBlindBox) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

func (x *SimpleBlindBox) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *SimpleBlindBox) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *SimpleBlindBox) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *SimpleBlindBox) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SimpleBlindBox) GetStartAt() uint64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *SimpleBlindBox) GetEndAt() uint64 {
	if x != nil {
		return x.EndAt
	}
	return 0
}

func (x *SimpleBlindBox) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *SimpleBlindBox) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SimpleBlindBox) GetRemain() uint64 {
	if x != nil {
		return x.Remain
	}
	return 0
}

func (x *SimpleBlindBox) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

// BlindBoxTop 返回 Top 盲盒
type BlindBoxTop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Box   *SimpleBlindBox `protobuf:"bytes,1,opt,name=box,proto3" json:"box"`
	Works []*SimpleWork   `protobuf:"bytes,2,rep,name=works,proto3" json:"works"`
}

func (x *BlindBoxTop) Reset() {
	*x = BlindBoxTop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxTop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxTop) ProtoMessage() {}

func (x *BlindBoxTop) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxTop.ProtoReflect.Descriptor instead.
func (*BlindBoxTop) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{4}
}

func (x *BlindBoxTop) GetBox() *SimpleBlindBox {
	if x != nil {
		return x.Box
	}
	return nil
}

func (x *BlindBoxTop) GetWorks() []*SimpleWork {
	if x != nil {
		return x.Works
	}
	return nil
}

// BlindBoxTop 盲盒首页
type BlindBoxTopPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num uint64 `protobuf:"varint,1,opt,name=num,proto3" json:"num"`
}

func (x *BlindBoxTopPost) Reset() {
	*x = BlindBoxTopPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxTopPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxTopPost) ProtoMessage() {}

func (x *BlindBoxTopPost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxTopPost.ProtoReflect.Descriptor instead.
func (*BlindBoxTopPost) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{5}
}

func (x *BlindBoxTopPost) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// BlindBoxDetailPost 盲盒详情
type BlindBoxDetailPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Num uint64 `protobuf:"varint,2,opt,name=num,proto3" json:"num"`
}

func (x *BlindBoxDetailPost) Reset() {
	*x = BlindBoxDetailPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxDetailPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxDetailPost) ProtoMessage() {}

func (x *BlindBoxDetailPost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxDetailPost.ProtoReflect.Descriptor instead.
func (*BlindBoxDetailPost) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{6}
}

func (x *BlindBoxDetailPost) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlindBoxDetailPost) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// PurchaseBlindBoxPost 购买盲盒
type PurchaseBlindBoxPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Num uint64 `protobuf:"varint,2,opt,name=num,proto3" json:"num"`
}

func (x *PurchaseBlindBoxPost) Reset() {
	*x = PurchaseBlindBoxPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PurchaseBlindBoxPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseBlindBoxPost) ProtoMessage() {}

func (x *PurchaseBlindBoxPost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseBlindBoxPost.ProtoReflect.Descriptor instead.
func (*PurchaseBlindBoxPost) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{7}
}

func (x *PurchaseBlindBoxPost) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PurchaseBlindBoxPost) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

// CreateBlindBoxPost 创建盲盒
type CreateBlindBoxPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractId   uint64  `protobuf:"varint,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id"`
	Title        string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title"`
	SubTitle     string  `protobuf:"bytes,4,opt,name=sub_title,json=subTitle,proto3" json:"sub_title"`
	Description  string  `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	Cover        string  `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover"`
	Background   string  `protobuf:"bytes,7,opt,name=background,proto3" json:"background"`
	Series       string  `protobuf:"bytes,8,opt,name=series,proto3" json:"series"`
	Price        float32 `protobuf:"fixed32,9,opt,name=price,proto3" json:"price"`
	StartAt      string  `protobuf:"bytes,10,opt,name=start_at,json=startAt,proto3" json:"start_at"`
	EndAt        string  `protobuf:"bytes,11,opt,name=end_at,json=endAt,proto3" json:"end_at"`
	Introduction string  `protobuf:"bytes,12,opt,name=introduction,proto3" json:"introduction"`
}

func (x *CreateBlindBoxPost) Reset() {
	*x = CreateBlindBoxPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBlindBoxPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBlindBoxPost) ProtoMessage() {}

func (x *CreateBlindBoxPost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBlindBoxPost.ProtoReflect.Descriptor instead.
func (*CreateBlindBoxPost) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBlindBoxPost) GetContractId() uint64 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

func (x *CreateBlindBoxPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBlindBoxPost) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *CreateBlindBoxPost) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBlindBoxPost) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreateBlindBoxPost) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *CreateBlindBoxPost) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *CreateBlindBoxPost) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateBlindBoxPost) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *CreateBlindBoxPost) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *CreateBlindBoxPost) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

// UpdateBlindBoxPost 更新盲盒
type UpdateBlindBoxPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64  `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	ContractId   uint64  `protobuf:"varint,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id"`
	Title        string  `protobuf:"bytes,3,opt,name=title,proto3" json:"title"`
	SubTitle     string  `protobuf:"bytes,4,opt,name=sub_title,json=subTitle,proto3" json:"sub_title"`
	Description  string  `protobuf:"bytes,5,opt,name=description,proto3" json:"description"`
	Cover        string  `protobuf:"bytes,6,opt,name=cover,proto3" json:"cover"`
	Background   string  `protobuf:"bytes,7,opt,name=background,proto3" json:"background"`
	Series       string  `protobuf:"bytes,8,opt,name=series,proto3" json:"series"`
	Price        float32 `protobuf:"fixed32,9,opt,name=price,proto3" json:"price"`
	StartAt      string  `protobuf:"bytes,10,opt,name=start_at,json=startAt,proto3" json:"start_at"`
	EndAt        string  `protobuf:"bytes,11,opt,name=end_at,json=endAt,proto3" json:"end_at"`
	Introduction string  `protobuf:"bytes,12,opt,name=introduction,proto3" json:"introduction"`
}

func (x *UpdateBlindBoxPost) Reset() {
	*x = UpdateBlindBoxPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateBlindBoxPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBlindBoxPost) ProtoMessage() {}

func (x *UpdateBlindBoxPost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBlindBoxPost.ProtoReflect.Descriptor instead.
func (*UpdateBlindBoxPost) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateBlindBoxPost) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateBlindBoxPost) GetContractId() uint64 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

func (x *UpdateBlindBoxPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateBlindBoxPost) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *UpdateBlindBoxPost) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateBlindBoxPost) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *UpdateBlindBoxPost) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *UpdateBlindBoxPost) GetSeries() string {
	if x != nil {
		return x.Series
	}
	return ""
}

func (x *UpdateBlindBoxPost) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateBlindBoxPost) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *UpdateBlindBoxPost) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *UpdateBlindBoxPost) GetIntroduction() string {
	if x != nil {
		return x.Introduction
	}
	return ""
}

// BlindBoxResponse 返回 盲盒基础信息
type BlindBoxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *BlindBox `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *BlindBoxResponse) Reset() {
	*x = BlindBoxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxResponse) ProtoMessage() {}

func (x *BlindBoxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxResponse.ProtoReflect.Descriptor instead.
func (*BlindBoxResponse) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{10}
}

func (x *BlindBoxResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlindBoxResponse) GetData() *BlindBox {
	if x != nil {
		return x.Data
	}
	return nil
}

// BlindBoxTopResponse 返回 盲盒首页
type BlindBoxTopResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *BlindBoxTop `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *BlindBoxTopResponse) Reset() {
	*x = BlindBoxTopResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxTopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxTopResponse) ProtoMessage() {}

func (x *BlindBoxTopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxTopResponse.ProtoReflect.Descriptor instead.
func (*BlindBoxTopResponse) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{11}
}

func (x *BlindBoxTopResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlindBoxTopResponse) GetData() *BlindBoxTop {
	if x != nil {
		return x.Data
	}
	return nil
}

// BlindBoxDetailResponse
type BlindBoxDetailResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BlindBoxDetailResponse) Reset() {
	*x = BlindBoxDetailResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxDetailResponse) ProtoMessage() {}

func (x *BlindBoxDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxDetailResponse.ProtoReflect.Descriptor instead.
func (*BlindBoxDetailResponse) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{12}
}

// BlindBoxPaginationResponse 返回 分页
type BlindBoxPaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                                `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *BlindBoxPaginationResponse_BlindBoxs `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *BlindBoxPaginationResponse) Reset() {
	*x = BlindBoxPaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxPaginationResponse) ProtoMessage() {}

func (x *BlindBoxPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxPaginationResponse.ProtoReflect.Descriptor instead.
func (*BlindBoxPaginationResponse) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{13}
}

func (x *BlindBoxPaginationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlindBoxPaginationResponse) GetData() *BlindBoxPaginationResponse_BlindBoxs {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlindBoxPaginationResponse_BlindBoxs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*BlindBox `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total int64       `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (x *BlindBoxPaginationResponse_BlindBoxs) Reset() {
	*x = BlindBoxPaginationResponse_BlindBoxs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxPaginationResponse_BlindBoxs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxPaginationResponse_BlindBoxs) ProtoMessage() {}

func (x *BlindBoxPaginationResponse_BlindBoxs) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxPaginationResponse_BlindBoxs.ProtoReflect.Descriptor instead.
func (*BlindBoxPaginationResponse_BlindBoxs) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_proto_rawDescGZIP(), []int{13, 0}
}

func (x *BlindBoxPaginationResponse_BlindBoxs) GetList() []*BlindBox {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *BlindBoxPaginationResponse_BlindBoxs) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_nft_blind_box_proto protoreflect.FileDescriptor

var file_nft_blind_box_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6e, 0x66, 0x74, 0x2f, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x78, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6e, 0x66, 0x74, 0x1a, 0x0e, 0x6e, 0x66, 0x74, 0x2f,
	0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe7, 0x02, 0x0a, 0x08, 0x42,
	0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x74, 0x6f, 0x70, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x74, 0x6f, 0x70, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x8a, 0x02, 0x0a, 0x0f, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f,
	0x78, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x6c, 0x69, 0x6e,
	0x64, 0x5f, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a,
	0x62, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x77, 0x6f,
	0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x77, 0x6f, 0x72,
	0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x70,
	0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x70, 0x72, 0x6f, 0x62, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41,
	0x74, 0x22, 0x90, 0x01, 0x0a, 0x14, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x49, 0x6e,
	0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0c, 0x62, 0x6c,
	0x69, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0a, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x22, 0x8d, 0x03, 0x0a, 0x0e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x42,
	0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c,
	0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b,
	0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12,
	0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x22, 0x5b, 0x0a, 0x0b, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78,
	0x54, 0x6f, 0x70, 0x12, 0x25, 0x0a, 0x03, 0x62, 0x6f, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x42, 0x6c, 0x69,
	0x6e, 0x64, 0x42, 0x6f, 0x78, 0x52, 0x03, 0x62, 0x6f, 0x78, 0x12, 0x25, 0x0a, 0x05, 0x77, 0x6f,
	0x72, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6e, 0x66, 0x74, 0x2e,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x6b,
	0x73, 0x22, 0x23, 0x0a, 0x0f, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x54, 0x6f, 0x70,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x36, 0x0a, 0x12, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42,
	0x6f, 0x78, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0x38,
	0x0a, 0x14, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42,
	0x6f, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22, 0xc4, 0x02, 0x0a, 0x12, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62,
	0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61,
	0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65, 0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x69,
	0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0xd4, 0x02, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42,
	0x6f, 0x78, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76,
	0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75,
	0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x65,
	0x6e, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64,
	0x41, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x69, 0x6e, 0x74, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4f, 0x0a, 0x10, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42,
	0x6f, 0x78, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f,
	0x78, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x55, 0x0a, 0x13, 0x42, 0x6c, 0x69, 0x6e, 0x64,
	0x42, 0x6f, 0x78, 0x54, 0x6f, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x42, 0x6c, 0x69,
	0x6e, 0x64, 0x42, 0x6f, 0x78, 0x54, 0x6f, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x18,
	0x0a, 0x16, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x1a, 0x42, 0x6c, 0x69,
	0x6e, 0x64, 0x42, 0x6f, 0x78, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x29, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x1a, 0x44, 0x0a, 0x09, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x73, 0x12, 0x21, 0x0a,
	0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x66,
	0x74, 0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nft_blind_box_proto_rawDescOnce sync.Once
	file_nft_blind_box_proto_rawDescData = file_nft_blind_box_proto_rawDesc
)

func file_nft_blind_box_proto_rawDescGZIP() []byte {
	file_nft_blind_box_proto_rawDescOnce.Do(func() {
		file_nft_blind_box_proto_rawDescData = protoimpl.X.CompressGZIP(file_nft_blind_box_proto_rawDescData)
	})
	return file_nft_blind_box_proto_rawDescData
}

var file_nft_blind_box_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_nft_blind_box_proto_goTypes = []interface{}{
	(*BlindBox)(nil),                             // 0: nft.BlindBox
	(*BlindBoxContent)(nil),                      // 1: nft.BlindBoxContent
	(*BlindBoxIntroduction)(nil),                 // 2: nft.BlindBoxIntroduction
	(*SimpleBlindBox)(nil),                       // 3: nft.SimpleBlindBox
	(*BlindBoxTop)(nil),                          // 4: nft.BlindBoxTop
	(*BlindBoxTopPost)(nil),                      // 5: nft.BlindBoxTopPost
	(*BlindBoxDetailPost)(nil),                   // 6: nft.BlindBoxDetailPost
	(*PurchaseBlindBoxPost)(nil),                 // 7: nft.PurchaseBlindBoxPost
	(*CreateBlindBoxPost)(nil),                   // 8: nft.CreateBlindBoxPost
	(*UpdateBlindBoxPost)(nil),                   // 9: nft.UpdateBlindBoxPost
	(*BlindBoxResponse)(nil),                     // 10: nft.BlindBoxResponse
	(*BlindBoxTopResponse)(nil),                  // 11: nft.BlindBoxTopResponse
	(*BlindBoxDetailResponse)(nil),               // 12: nft.BlindBoxDetailResponse
	(*BlindBoxPaginationResponse)(nil),           // 13: nft.BlindBoxPaginationResponse
	(*BlindBoxPaginationResponse_BlindBoxs)(nil), // 14: nft.BlindBoxPaginationResponse.BlindBoxs
	(*SimpleWork)(nil),                           // 15: nft.SimpleWork
}
var file_nft_blind_box_proto_depIdxs = []int32{
	3,  // 0: nft.BlindBoxTop.box:type_name -> nft.SimpleBlindBox
	15, // 1: nft.BlindBoxTop.works:type_name -> nft.SimpleWork
	0,  // 2: nft.BlindBoxResponse.data:type_name -> nft.BlindBox
	4,  // 3: nft.BlindBoxTopResponse.data:type_name -> nft.BlindBoxTop
	14, // 4: nft.BlindBoxPaginationResponse.data:type_name -> nft.BlindBoxPaginationResponse.BlindBoxs
	0,  // 5: nft.BlindBoxPaginationResponse.BlindBoxs.list:type_name -> nft.BlindBox
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nft_blind_box_proto_init() }
func file_nft_blind_box_proto_init() {
	if File_nft_blind_box_proto != nil {
		return
	}
	file_nft_work_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_nft_blind_box_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxIntroduction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleBlindBox); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxTop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxTopPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxDetailPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PurchaseBlindBoxPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBlindBoxPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateBlindBoxPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxTopResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxDetailResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxPaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxPaginationResponse_BlindBoxs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nft_blind_box_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nft_blind_box_proto_goTypes,
		DependencyIndexes: file_nft_blind_box_proto_depIdxs,
		MessageInfos:      file_nft_blind_box_proto_msgTypes,
	}.Build()
	File_nft_blind_box_proto = out.File
	file_nft_blind_box_proto_rawDesc = nil
	file_nft_blind_box_proto_goTypes = nil
	file_nft_blind_box_proto_depIdxs = nil
}
