// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: nft/blind_box_exchange.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressBlindBoxExchangePost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
}

func (x *AddressBlindBoxExchangePost) Reset() {
	*x = AddressBlindBoxExchangePost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_exchange_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressBlindBoxExchangePost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressBlindBoxExchangePost) ProtoMessage() {}

func (x *AddressBlindBoxExchangePost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_exchange_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressBlindBoxExchangePost.ProtoReflect.Descriptor instead.
func (*AddressBlindBoxExchangePost) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_exchange_proto_rawDescGZIP(), []int{0}
}

func (x *AddressBlindBoxExchangePost) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// CountBlindBoxExchangeResponse 计算可以免费兑换的盲盒
type CountBlindBoxExchangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    uint64 `protobuf:"varint,2,opt,name=data,proto3" json:"data"`
}

func (x *CountBlindBoxExchangeResponse) Reset() {
	*x = CountBlindBoxExchangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_exchange_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CountBlindBoxExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountBlindBoxExchangeResponse) ProtoMessage() {}

func (x *CountBlindBoxExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_exchange_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountBlindBoxExchangeResponse.ProtoReflect.Descriptor instead.
func (*CountBlindBoxExchangeResponse) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *CountBlindBoxExchangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CountBlindBoxExchangeResponse) GetData() uint64 {
	if x != nil {
		return x.Data
	}
	return 0
}

// BlineBoxExchangeResponse 兑换免费盲盒
type BlindBoxExchangeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                         `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *BlindBoxExchangeResponse_Sign `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *BlindBoxExchangeResponse) Reset() {
	*x = BlindBoxExchangeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_exchange_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxExchangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxExchangeResponse) ProtoMessage() {}

func (x *BlindBoxExchangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_exchange_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxExchangeResponse.ProtoReflect.Descriptor instead.
func (*BlindBoxExchangeResponse) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_exchange_proto_rawDescGZIP(), []int{2}
}

func (x *BlindBoxExchangeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BlindBoxExchangeResponse) GetData() *BlindBoxExchangeResponse_Sign {
	if x != nil {
		return x.Data
	}
	return nil
}

type BlindBoxExchangeResponse_Sign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature string `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature"`
	Code      uint64 `protobuf:"varint,2,opt,name=code,proto3" json:"code"`
	Timestamp uint64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp"`
}

func (x *BlindBoxExchangeResponse_Sign) Reset() {
	*x = BlindBoxExchangeResponse_Sign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_blind_box_exchange_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlindBoxExchangeResponse_Sign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlindBoxExchangeResponse_Sign) ProtoMessage() {}

func (x *BlindBoxExchangeResponse_Sign) ProtoReflect() protoreflect.Message {
	mi := &file_nft_blind_box_exchange_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlindBoxExchangeResponse_Sign.ProtoReflect.Descriptor instead.
func (*BlindBoxExchangeResponse_Sign) Descriptor() ([]byte, []int) {
	return file_nft_blind_box_exchange_proto_rawDescGZIP(), []int{2, 0}
}

func (x *BlindBoxExchangeResponse_Sign) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *BlindBoxExchangeResponse_Sign) GetCode() uint64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BlindBoxExchangeResponse_Sign) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_nft_blind_box_exchange_proto protoreflect.FileDescriptor

var file_nft_blind_box_exchange_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6e, 0x66, 0x74, 0x2f, 0x62, 0x6c, 0x69, 0x6e, 0x64, 0x5f, 0x62, 0x6f, 0x78, 0x5f,
	0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x6e, 0x66, 0x74, 0x22, 0x37, 0x0a, 0x1b, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x6c,
	0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x50, 0x6f,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x4d, 0x0a, 0x1d,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x45, 0x78, 0x63,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xc4, 0x01, 0x0a, 0x18,
	0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x36, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x42, 0x6c, 0x69, 0x6e, 0x64, 0x42, 0x6f, 0x78, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x69, 0x67, 0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x56, 0x0a, 0x04, 0x53, 0x69,
	0x67, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nft_blind_box_exchange_proto_rawDescOnce sync.Once
	file_nft_blind_box_exchange_proto_rawDescData = file_nft_blind_box_exchange_proto_rawDesc
)

func file_nft_blind_box_exchange_proto_rawDescGZIP() []byte {
	file_nft_blind_box_exchange_proto_rawDescOnce.Do(func() {
		file_nft_blind_box_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(file_nft_blind_box_exchange_proto_rawDescData)
	})
	return file_nft_blind_box_exchange_proto_rawDescData
}

var file_nft_blind_box_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nft_blind_box_exchange_proto_goTypes = []interface{}{
	(*AddressBlindBoxExchangePost)(nil),   // 0: nft.AddressBlindBoxExchangePost
	(*CountBlindBoxExchangeResponse)(nil), // 1: nft.CountBlindBoxExchangeResponse
	(*BlindBoxExchangeResponse)(nil),      // 2: nft.BlindBoxExchangeResponse
	(*BlindBoxExchangeResponse_Sign)(nil), // 3: nft.BlindBoxExchangeResponse.Sign
}
var file_nft_blind_box_exchange_proto_depIdxs = []int32{
	3, // 0: nft.BlindBoxExchangeResponse.data:type_name -> nft.BlindBoxExchangeResponse.Sign
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_nft_blind_box_exchange_proto_init() }
func file_nft_blind_box_exchange_proto_init() {
	if File_nft_blind_box_exchange_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nft_blind_box_exchange_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressBlindBoxExchangePost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_exchange_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CountBlindBoxExchangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_exchange_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxExchangeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_blind_box_exchange_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlindBoxExchangeResponse_Sign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nft_blind_box_exchange_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nft_blind_box_exchange_proto_goTypes,
		DependencyIndexes: file_nft_blind_box_exchange_proto_depIdxs,
		MessageInfos:      file_nft_blind_box_exchange_proto_msgTypes,
	}.Build()
	File_nft_blind_box_exchange_proto = out.File
	file_nft_blind_box_exchange_proto_rawDesc = nil
	file_nft_blind_box_exchange_proto_goTypes = nil
	file_nft_blind_box_exchange_proto_depIdxs = nil
}
