// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: nft/contract.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contract 智能合约
type Contract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Type      uint64 `protobuf:"varint,2,opt,name=type,proto3" json:"type"`
	Address   string `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	Noise     string `protobuf:"bytes,4,opt,name=noise,proto3" json:"noise"`
	EncodeKey string `protobuf:"bytes,5,opt,name=encode_key,json=encodeKey,proto3" json:"encode_key"`
	Node      string `protobuf:"bytes,6,opt,name=node,proto3" json:"node"`
	Interval  uint64 `protobuf:"varint,7,opt,name=interval,proto3" json:"interval"`
	Status    uint64 `protobuf:"varint,8,opt,name=status,proto3" json:"status"`
	Checked   bool   `protobuf:"varint,9,opt,name=checked,proto3" json:"checked"`
	CreatedAt string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt string `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
}

func (x *Contract) Reset() {
	*x = Contract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_nft_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_nft_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Contract) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contract) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Contract) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Contract) GetNoise() string {
	if x != nil {
		return x.Noise
	}
	return ""
}

func (x *Contract) GetEncodeKey() string {
	if x != nil {
		return x.EncodeKey
	}
	return ""
}

func (x *Contract) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *Contract) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *Contract) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Contract) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

func (x *Contract) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Contract) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

// CreateContractPost 创建合约
type CreateContractPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type      uint64 `protobuf:"varint,2,opt,name=type,proto3" json:"type"`
	Address   string `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	Noise     string `protobuf:"bytes,4,opt,name=noise,proto3" json:"noise"`
	EncodeKey string `protobuf:"bytes,5,opt,name=encode_key,json=encodeKey,proto3" json:"encode_key"`
	Node      string `protobuf:"bytes,6,opt,name=node,proto3" json:"node"`
	Interval  uint64 `protobuf:"varint,7,opt,name=interval,proto3" json:"interval"`
}

func (x *CreateContractPost) Reset() {
	*x = CreateContractPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_contract_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateContractPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContractPost) ProtoMessage() {}

func (x *CreateContractPost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_contract_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContractPost.ProtoReflect.Descriptor instead.
func (*CreateContractPost) Descriptor() ([]byte, []int) {
	return file_nft_contract_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContractPost) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateContractPost) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateContractPost) GetNoise() string {
	if x != nil {
		return x.Noise
	}
	return ""
}

func (x *CreateContractPost) GetEncodeKey() string {
	if x != nil {
		return x.EncodeKey
	}
	return ""
}

func (x *CreateContractPost) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *CreateContractPost) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

// UpdateContractPost 更新合约
type UpdateContractPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	Type      uint64 `protobuf:"varint,2,opt,name=type,proto3" json:"type"`
	Address   string `protobuf:"bytes,3,opt,name=address,proto3" json:"address"`
	Noise     string `protobuf:"bytes,4,opt,name=noise,proto3" json:"noise"`
	EncodeKey string `protobuf:"bytes,5,opt,name=encode_key,json=encodeKey,proto3" json:"encode_key"`
	Node      string `protobuf:"bytes,6,opt,name=node,proto3" json:"node"`
	Interval  uint64 `protobuf:"varint,7,opt,name=interval,proto3" json:"interval"`
}

func (x *UpdateContractPost) Reset() {
	*x = UpdateContractPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_contract_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateContractPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContractPost) ProtoMessage() {}

func (x *UpdateContractPost) ProtoReflect() protoreflect.Message {
	mi := &file_nft_contract_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContractPost.ProtoReflect.Descriptor instead.
func (*UpdateContractPost) Descriptor() ([]byte, []int) {
	return file_nft_contract_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateContractPost) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateContractPost) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateContractPost) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateContractPost) GetNoise() string {
	if x != nil {
		return x.Noise
	}
	return ""
}

func (x *UpdateContractPost) GetEncodeKey() string {
	if x != nil {
		return x.EncodeKey
	}
	return ""
}

func (x *UpdateContractPost) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *UpdateContractPost) GetInterval() uint64 {
	if x != nil {
		return x.Interval
	}
	return 0
}

// ContractResponse 返回合约
type ContractResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string    `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *Contract `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *ContractResponse) Reset() {
	*x = ContractResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_contract_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractResponse) ProtoMessage() {}

func (x *ContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_contract_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractResponse.ProtoReflect.Descriptor instead.
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return file_nft_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ContractResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContractResponse) GetData() *Contract {
	if x != nil {
		return x.Data
	}
	return nil
}

// ContractsResponse 返回 合约列表
type ContractsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string      `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    []*Contract `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
}

func (x *ContractsResponse) Reset() {
	*x = ContractsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_contract_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractsResponse) ProtoMessage() {}

func (x *ContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_contract_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractsResponse.ProtoReflect.Descriptor instead.
func (*ContractsResponse) Descriptor() ([]byte, []int) {
	return file_nft_contract_proto_rawDescGZIP(), []int{4}
}

func (x *ContractsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContractsResponse) GetData() []*Contract {
	if x != nil {
		return x.Data
	}
	return nil
}

// ContractPaginationResponse 返回 合约分页
type ContractPaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                                `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *ContractPaginationResponse_Contracts `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *ContractPaginationResponse) Reset() {
	*x = ContractPaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_contract_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractPaginationResponse) ProtoMessage() {}

func (x *ContractPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nft_contract_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractPaginationResponse.ProtoReflect.Descriptor instead.
func (*ContractPaginationResponse) Descriptor() ([]byte, []int) {
	return file_nft_contract_proto_rawDescGZIP(), []int{5}
}

func (x *ContractPaginationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ContractPaginationResponse) GetData() *ContractPaginationResponse_Contracts {
	if x != nil {
		return x.Data
	}
	return nil
}

type ContractPaginationResponse_Contracts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Contract `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total int64       `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (x *ContractPaginationResponse_Contracts) Reset() {
	*x = ContractPaginationResponse_Contracts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nft_contract_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractPaginationResponse_Contracts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractPaginationResponse_Contracts) ProtoMessage() {}

func (x *ContractPaginationResponse_Contracts) ProtoReflect() protoreflect.Message {
	mi := &file_nft_contract_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractPaginationResponse_Contracts.ProtoReflect.Descriptor instead.
func (*ContractPaginationResponse_Contracts) Descriptor() ([]byte, []int) {
	return file_nft_contract_proto_rawDescGZIP(), []int{5, 0}
}

func (x *ContractPaginationResponse_Contracts) GetList() []*Contract {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *ContractPaginationResponse_Contracts) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_nft_contract_proto protoreflect.FileDescriptor

var file_nft_contract_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6e, 0x66, 0x74, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x6e, 0x66, 0x74, 0x22, 0x9d, 0x02, 0x0a, 0x08, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x69, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xa7, 0x01, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x6f, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e,
	0x6f, 0x69, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x22, 0xb7, 0x01, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x69, 0x73,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x69, 0x73, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x76, 0x61, 0x6c, 0x22, 0x4f, 0x0a,
	0x10, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x66, 0x74, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x50,
	0x0a, 0x11, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x66,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xbb, 0x01, 0x0a, 0x1a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x73, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x44, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x12, 0x21, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6e, 0x66, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_nft_contract_proto_rawDescOnce sync.Once
	file_nft_contract_proto_rawDescData = file_nft_contract_proto_rawDesc
)

func file_nft_contract_proto_rawDescGZIP() []byte {
	file_nft_contract_proto_rawDescOnce.Do(func() {
		file_nft_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_nft_contract_proto_rawDescData)
	})
	return file_nft_contract_proto_rawDescData
}

var file_nft_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_nft_contract_proto_goTypes = []interface{}{
	(*Contract)(nil),                             // 0: nft.Contract
	(*CreateContractPost)(nil),                   // 1: nft.CreateContractPost
	(*UpdateContractPost)(nil),                   // 2: nft.UpdateContractPost
	(*ContractResponse)(nil),                     // 3: nft.ContractResponse
	(*ContractsResponse)(nil),                    // 4: nft.ContractsResponse
	(*ContractPaginationResponse)(nil),           // 5: nft.ContractPaginationResponse
	(*ContractPaginationResponse_Contracts)(nil), // 6: nft.ContractPaginationResponse.Contracts
}
var file_nft_contract_proto_depIdxs = []int32{
	0, // 0: nft.ContractResponse.data:type_name -> nft.Contract
	0, // 1: nft.ContractsResponse.data:type_name -> nft.Contract
	6, // 2: nft.ContractPaginationResponse.data:type_name -> nft.ContractPaginationResponse.Contracts
	0, // 3: nft.ContractPaginationResponse.Contracts.list:type_name -> nft.Contract
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_nft_contract_proto_init() }
func file_nft_contract_proto_init() {
	if File_nft_contract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nft_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Contract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_contract_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateContractPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_contract_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateContractPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_contract_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_contract_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_contract_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractPaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nft_contract_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractPaginationResponse_Contracts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nft_contract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_nft_contract_proto_goTypes,
		DependencyIndexes: file_nft_contract_proto_depIdxs,
		MessageInfos:      file_nft_contract_proto_msgTypes,
	}.Build()
	File_nft_contract_proto = out.File
	file_nft_contract_proto_rawDesc = nil
	file_nft_contract_proto_goTypes = nil
	file_nft_contract_proto_depIdxs = nil
}
