// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: member/member_login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SimpleMember 会员信息
type SimpleMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description"`
	AvatarPath    uint64 `protobuf:"varint,4,opt,name=avatar_path,json=avatarPath,proto3" json:"avatar_path"`
	AvatarUrl     string `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url"`
	Address       string `protobuf:"bytes,6,opt,name=address,proto3" json:"address"`
	InviteCode    string `protobuf:"bytes,7,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code"`
	InviteAddress string `protobuf:"bytes,8,opt,name=invite_address,json=inviteAddress,proto3" json:"invite_address"`
	Email         string `protobuf:"bytes,9,opt,name=email,proto3" json:"email"`
	Facebook      string `protobuf:"bytes,10,opt,name=facebook,proto3" json:"facebook"`
	Twitter       string `protobuf:"bytes,11,opt,name=twitter,proto3" json:"twitter"`
}

func (x *SimpleMember) Reset() {
	*x = SimpleMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleMember) ProtoMessage() {}

func (x *SimpleMember) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleMember.ProtoReflect.Descriptor instead.
func (*SimpleMember) Descriptor() ([]byte, []int) {
	return file_member_member_login_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleMember) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SimpleMember) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SimpleMember) GetAvatarPath() uint64 {
	if x != nil {
		return x.AvatarPath
	}
	return 0
}

func (x *SimpleMember) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *SimpleMember) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *SimpleMember) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

func (x *SimpleMember) GetInviteAddress() string {
	if x != nil {
		return x.InviteAddress
	}
	return ""
}

func (x *SimpleMember) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SimpleMember) GetFacebook() string {
	if x != nil {
		return x.Facebook
	}
	return ""
}

func (x *SimpleMember) GetTwitter() string {
	if x != nil {
		return x.Twitter
	}
	return ""
}

// MemberHashPost 获取 hash
type MemberHashPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address"`
}

func (x *MemberHashPost) Reset() {
	*x = MemberHashPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_login_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberHashPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberHashPost) ProtoMessage() {}

func (x *MemberHashPost) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_login_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberHashPost.ProtoReflect.Descriptor instead.
func (*MemberHashPost) Descriptor() ([]byte, []int) {
	return file_member_member_login_proto_rawDescGZIP(), []int{1}
}

func (x *MemberHashPost) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// MemberLoginPost 会员登录
type MemberLoginPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash       string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash"`
	Signature  string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature"`
	InviteCode string `protobuf:"bytes,3,opt,name=invite_code,json=inviteCode,proto3" json:"invite_code"`
}

func (x *MemberLoginPost) Reset() {
	*x = MemberLoginPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_login_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberLoginPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLoginPost) ProtoMessage() {}

func (x *MemberLoginPost) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_login_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLoginPost.ProtoReflect.Descriptor instead.
func (*MemberLoginPost) Descriptor() ([]byte, []int) {
	return file_member_member_login_proto_rawDescGZIP(), []int{2}
}

func (x *MemberLoginPost) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *MemberLoginPost) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *MemberLoginPost) GetInviteCode() string {
	if x != nil {
		return x.InviteCode
	}
	return ""
}

// MemberHashResponse 返回 Hash
type MemberHashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    string `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *MemberHashResponse) Reset() {
	*x = MemberHashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_login_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberHashResponse) ProtoMessage() {}

func (x *MemberHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_login_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberHashResponse.ProtoReflect.Descriptor instead.
func (*MemberHashResponse) Descriptor() ([]byte, []int) {
	return file_member_member_login_proto_rawDescGZIP(), []int{3}
}

func (x *MemberHashResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MemberHashResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// MemberLoginResponse 会员登录返回
type MemberLoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                     `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *MemberLoginResponse_Login `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *MemberLoginResponse) Reset() {
	*x = MemberLoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_login_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLoginResponse) ProtoMessage() {}

func (x *MemberLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_login_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLoginResponse.ProtoReflect.Descriptor instead.
func (*MemberLoginResponse) Descriptor() ([]byte, []int) {
	return file_member_member_login_proto_rawDescGZIP(), []int{4}
}

func (x *MemberLoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MemberLoginResponse) GetData() *MemberLoginResponse_Login {
	if x != nil {
		return x.Data
	}
	return nil
}

type MemberLoginResponse_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Member  *SimpleMember `protobuf:"bytes,1,opt,name=member,proto3" json:"member"`
	Token   string        `protobuf:"bytes,2,opt,name=token,proto3" json:"token"`
	Expired uint64        `protobuf:"varint,3,opt,name=expired,proto3" json:"expired"`
}

func (x *MemberLoginResponse_Login) Reset() {
	*x = MemberLoginResponse_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_member_member_login_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MemberLoginResponse_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLoginResponse_Login) ProtoMessage() {}

func (x *MemberLoginResponse_Login) ProtoReflect() protoreflect.Message {
	mi := &file_member_member_login_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLoginResponse_Login.ProtoReflect.Descriptor instead.
func (*MemberLoginResponse_Login) Descriptor() ([]byte, []int) {
	return file_member_member_login_proto_rawDescGZIP(), []int{4, 0}
}

func (x *MemberLoginResponse_Login) GetMember() *SimpleMember {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *MemberLoginResponse_Login) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MemberLoginResponse_Login) GetExpired() uint64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

var File_member_member_login_proto protoreflect.FileDescriptor

var file_member_member_login_proto_rawDesc = []byte{
	0x0a, 0x19, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x5f,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6d, 0x65, 0x6d,
	0x62, 0x65, 0x72, 0x22, 0xb2, 0x02, 0x0a, 0x0c, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x61, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1d, 0x0a, 0x0a, 0x61,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x76, 0x69, 0x74,
	0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x69,
	0x6e, 0x76, 0x69, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x18, 0x0a,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x63, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x12, 0x18,
	0x0a, 0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x74, 0x77, 0x69, 0x74, 0x74, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x0e, 0x4d, 0x65, 0x6d, 0x62,
	0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x64, 0x0a, 0x0f, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e, 0x76,
	0x69, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x69, 0x6e, 0x76, 0x69, 0x74, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x42, 0x0a, 0x12, 0x4d, 0x65,
	0x6d, 0x62, 0x65, 0x72, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xcd,
	0x01, 0x0a, 0x13, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x35, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21,
	0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x4c, 0x6f,
	0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x65, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x12, 0x2c, 0x0a, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x06, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_member_member_login_proto_rawDescOnce sync.Once
	file_member_member_login_proto_rawDescData = file_member_member_login_proto_rawDesc
)

func file_member_member_login_proto_rawDescGZIP() []byte {
	file_member_member_login_proto_rawDescOnce.Do(func() {
		file_member_member_login_proto_rawDescData = protoimpl.X.CompressGZIP(file_member_member_login_proto_rawDescData)
	})
	return file_member_member_login_proto_rawDescData
}

var file_member_member_login_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_member_member_login_proto_goTypes = []interface{}{
	(*SimpleMember)(nil),              // 0: member.SimpleMember
	(*MemberHashPost)(nil),            // 1: member.MemberHashPost
	(*MemberLoginPost)(nil),           // 2: member.MemberLoginPost
	(*MemberHashResponse)(nil),        // 3: member.MemberHashResponse
	(*MemberLoginResponse)(nil),       // 4: member.MemberLoginResponse
	(*MemberLoginResponse_Login)(nil), // 5: member.MemberLoginResponse.Login
}
var file_member_member_login_proto_depIdxs = []int32{
	5, // 0: member.MemberLoginResponse.data:type_name -> member.MemberLoginResponse.Login
	0, // 1: member.MemberLoginResponse.Login.member:type_name -> member.SimpleMember
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_member_member_login_proto_init() }
func file_member_member_login_proto_init() {
	if File_member_member_login_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_member_member_login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_login_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberHashPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_login_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberLoginPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_login_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberHashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_login_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberLoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_member_member_login_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MemberLoginResponse_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_member_member_login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_member_member_login_proto_goTypes,
		DependencyIndexes: file_member_member_login_proto_depIdxs,
		MessageInfos:      file_member_member_login_proto_msgTypes,
	}.Build()
	File_member_member_login_proto = out.File
	file_member_member_login_proto_rawDesc = nil
	file_member_member_login_proto_goTypes = nil
	file_member_member_login_proto_depIdxs = nil
}
