// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: remix/remix_work.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemixWork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	RemixId     uint64         `protobuf:"varint,2,opt,name=remix_id,json=remixId,proto3" json:"remix_id"`
	Type        uint64         `protobuf:"varint,3,opt,name=type,proto3" json:"type"`
	Title       string         `protobuf:"bytes,4,opt,name=title,proto3" json:"title"`
	SubTitle    string         `protobuf:"bytes,5,opt,name=sub_title,json=subTitle,proto3" json:"sub_title"`
	Description string         `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	Rarity      uint64         `protobuf:"varint,7,opt,name=rarity,proto3" json:"rarity"`
	Cover       string         `protobuf:"bytes,8,opt,name=cover,proto3" json:"cover"`
	Path        string         `protobuf:"bytes,9,opt,name=path,proto3" json:"path"`
	Remix       string         `protobuf:"bytes,10,opt,name=remix,proto3" json:"remix"`
	Used        uint64         `protobuf:"varint,11,opt,name=used,proto3" json:"used"`
	Status      uint64         `protobuf:"varint,12,opt,name=status,proto3" json:"status"`
	Checked     bool           `protobuf:"varint,13,opt,name=checked,proto3" json:"checked"`
	CreatedAt   string         `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at"`
	UpdatedAt   string         `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at"`
	RemixInfo   *RelationRemix `protobuf:"bytes,16,opt,name=remix_info,json=remixInfo,proto3" json:"remix_info"`
}

func (x *RemixWork) Reset() {
	*x = RemixWork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemixWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemixWork) ProtoMessage() {}

func (x *RemixWork) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemixWork.ProtoReflect.Descriptor instead.
func (*RemixWork) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{0}
}

func (x *RemixWork) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RemixWork) GetRemixId() uint64 {
	if x != nil {
		return x.RemixId
	}
	return 0
}

func (x *RemixWork) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *RemixWork) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RemixWork) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *RemixWork) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RemixWork) GetRarity() uint64 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *RemixWork) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *RemixWork) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RemixWork) GetRemix() string {
	if x != nil {
		return x.Remix
	}
	return ""
}

func (x *RemixWork) GetUsed() uint64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *RemixWork) GetStatus() uint64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *RemixWork) GetChecked() bool {
	if x != nil {
		return x.Checked
	}
	return false
}

func (x *RemixWork) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *RemixWork) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RemixWork) GetRemixInfo() *RelationRemix {
	if x != nil {
		return x.RemixInfo
	}
	return nil
}

// DoRemixWorkPost 处理混合作品
type DoRemixWorkPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ContractId uint64 `protobuf:"varint,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id"`
	Hash       string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash"`
}

func (x *DoRemixWorkPost) Reset() {
	*x = DoRemixWorkPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoRemixWorkPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRemixWorkPost) ProtoMessage() {}

func (x *DoRemixWorkPost) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRemixWorkPost.ProtoReflect.Descriptor instead.
func (*DoRemixWorkPost) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{1}
}

func (x *DoRemixWorkPost) GetContractId() uint64 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

func (x *DoRemixWorkPost) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// RemixWorkPaginationPost 作品分页
type RemixWorkPaginationPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemixId uint64 `protobuf:"varint,1,opt,name=remix_id,json=remixId,proto3" json:"remix_id"`
	Page    uint64 `protobuf:"varint,2,opt,name=page,proto3" json:"page"`
	Size    uint64 `protobuf:"varint,3,opt,name=size,proto3" json:"size"`
}

func (x *RemixWorkPaginationPost) Reset() {
	*x = RemixWorkPaginationPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemixWorkPaginationPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemixWorkPaginationPost) ProtoMessage() {}

func (x *RemixWorkPaginationPost) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemixWorkPaginationPost.ProtoReflect.Descriptor instead.
func (*RemixWorkPaginationPost) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{2}
}

func (x *RemixWorkPaginationPost) GetRemixId() uint64 {
	if x != nil {
		return x.RemixId
	}
	return 0
}

func (x *RemixWorkPaginationPost) GetPage() uint64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *RemixWorkPaginationPost) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// CreateRemixWorkPost 创建 互动作品
type CreateRemixWorkPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RemixId     uint64 `protobuf:"varint,2,opt,name=remix_id,json=remixId,proto3" json:"remix_id"`
	Type        uint64 `protobuf:"varint,3,opt,name=type,proto3" json:"type"`
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title"`
	SubTitle    string `protobuf:"bytes,5,opt,name=sub_title,json=subTitle,proto3" json:"sub_title"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	Rarity      uint64 `protobuf:"varint,7,opt,name=rarity,proto3" json:"rarity"`
	Cover       string `protobuf:"bytes,8,opt,name=cover,proto3" json:"cover"`
	Path        string `protobuf:"bytes,9,opt,name=path,proto3" json:"path"`
}

func (x *CreateRemixWorkPost) Reset() {
	*x = CreateRemixWorkPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRemixWorkPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRemixWorkPost) ProtoMessage() {}

func (x *CreateRemixWorkPost) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRemixWorkPost.ProtoReflect.Descriptor instead.
func (*CreateRemixWorkPost) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{3}
}

func (x *CreateRemixWorkPost) GetRemixId() uint64 {
	if x != nil {
		return x.RemixId
	}
	return 0
}

func (x *CreateRemixWorkPost) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CreateRemixWorkPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateRemixWorkPost) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *CreateRemixWorkPost) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateRemixWorkPost) GetRarity() uint64 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *CreateRemixWorkPost) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *CreateRemixWorkPost) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// UpdateRemixWorkPost 更新 互动作品
type UpdateRemixWorkPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id"`
	RemixId     uint64 `protobuf:"varint,2,opt,name=remix_id,json=remixId,proto3" json:"remix_id"`
	Type        uint64 `protobuf:"varint,3,opt,name=type,proto3" json:"type"`
	Title       string `protobuf:"bytes,4,opt,name=title,proto3" json:"title"`
	SubTitle    string `protobuf:"bytes,5,opt,name=sub_title,json=subTitle,proto3" json:"sub_title"`
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description"`
	Rarity      uint64 `protobuf:"varint,7,opt,name=rarity,proto3" json:"rarity"`
	Cover       string `protobuf:"bytes,8,opt,name=cover,proto3" json:"cover"`
	Path        string `protobuf:"bytes,9,opt,name=path,proto3" json:"path"`
}

func (x *UpdateRemixWorkPost) Reset() {
	*x = UpdateRemixWorkPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateRemixWorkPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRemixWorkPost) ProtoMessage() {}

func (x *UpdateRemixWorkPost) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRemixWorkPost.ProtoReflect.Descriptor instead.
func (*UpdateRemixWorkPost) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateRemixWorkPost) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRemixWorkPost) GetRemixId() uint64 {
	if x != nil {
		return x.RemixId
	}
	return 0
}

func (x *UpdateRemixWorkPost) GetType() uint64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *UpdateRemixWorkPost) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateRemixWorkPost) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *UpdateRemixWorkPost) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateRemixWorkPost) GetRarity() uint64 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *UpdateRemixWorkPost) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *UpdateRemixWorkPost) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// RemixWorkResponse 返回
type RemixWorkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string     `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *RemixWork `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *RemixWorkResponse) Reset() {
	*x = RemixWorkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemixWorkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemixWorkResponse) ProtoMessage() {}

func (x *RemixWorkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemixWorkResponse.ProtoReflect.Descriptor instead.
func (*RemixWorkResponse) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{5}
}

func (x *RemixWorkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemixWorkResponse) GetData() *RemixWork {
	if x != nil {
		return x.Data
	}
	return nil
}

// RemixWorksResponse 返回
type RemixWorksResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string       `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    []*RemixWork `protobuf:"bytes,2,rep,name=data,proto3" json:"data"`
}

func (x *RemixWorksResponse) Reset() {
	*x = RemixWorksResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemixWorksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemixWorksResponse) ProtoMessage() {}

func (x *RemixWorksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemixWorksResponse.ProtoReflect.Descriptor instead.
func (*RemixWorksResponse) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{6}
}

func (x *RemixWorksResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemixWorksResponse) GetData() []*RemixWork {
	if x != nil {
		return x.Data
	}
	return nil
}

// RemixWorkPaginationResponse 返回分页
type RemixWorkPaginationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string                             `protobuf:"bytes,1,opt,name=message,proto3" json:"message"`
	Data    *RemixWorkPaginationResponse_Works `protobuf:"bytes,2,opt,name=data,proto3" json:"data"`
}

func (x *RemixWorkPaginationResponse) Reset() {
	*x = RemixWorkPaginationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemixWorkPaginationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemixWorkPaginationResponse) ProtoMessage() {}

func (x *RemixWorkPaginationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemixWorkPaginationResponse.ProtoReflect.Descriptor instead.
func (*RemixWorkPaginationResponse) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{7}
}

func (x *RemixWorkPaginationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemixWorkPaginationResponse) GetData() *RemixWorkPaginationResponse_Works {
	if x != nil {
		return x.Data
	}
	return nil
}

type RemixWorkPaginationResponse_Works struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*RemixWork `protobuf:"bytes,1,rep,name=list,proto3" json:"list"`
	Total int64        `protobuf:"varint,2,opt,name=total,proto3" json:"total"`
}

func (x *RemixWorkPaginationResponse_Works) Reset() {
	*x = RemixWorkPaginationResponse_Works{}
	if protoimpl.UnsafeEnabled {
		mi := &file_remix_remix_work_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemixWorkPaginationResponse_Works) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemixWorkPaginationResponse_Works) ProtoMessage() {}

func (x *RemixWorkPaginationResponse_Works) ProtoReflect() protoreflect.Message {
	mi := &file_remix_remix_work_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemixWorkPaginationResponse_Works.ProtoReflect.Descriptor instead.
func (*RemixWorkPaginationResponse_Works) Descriptor() ([]byte, []int) {
	return file_remix_remix_work_proto_rawDescGZIP(), []int{7, 0}
}

func (x *RemixWorkPaginationResponse_Works) GetList() []*RemixWork {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RemixWorkPaginationResponse_Works) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_remix_remix_work_proto protoreflect.FileDescriptor

var file_remix_remix_work_proto_rawDesc = []byte{
	0x0a, 0x16, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x5f, 0x77, 0x6f,
	0x72, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x1a,
	0x1a, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x2f, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x5f, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x03, 0x0a, 0x09,
	0x52, 0x65, 0x6d, 0x69, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x6d,
	0x69, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x65, 0x6d,
	0x69, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x72, 0x65, 0x6d, 0x69, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x64, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x75, 0x73, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x18, 0x0d, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x33, 0x0a, 0x0a, 0x72, 0x65, 0x6d,
	0x69, 0x78, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x72, 0x65, 0x6d, 0x69, 0x78, 0x2e, 0x52, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x6d, 0x69, 0x78, 0x52, 0x09, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x46,
	0x0a, 0x0f, 0x44, 0x6f, 0x52, 0x65, 0x6d, 0x69, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x73,
	0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x5c, 0x0a, 0x17, 0x52, 0x65, 0x6d, 0x69, 0x78, 0x57,
	0x6f, 0x72, 0x6b, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x50, 0x6f, 0x73,
	0x74, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x22, 0xdb, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x6d, 0x69, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08,
	0x72, 0x65, 0x6d, 0x69, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x72, 0x65, 0x6d, 0x69, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x22, 0xeb, 0x01, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x6d,
	0x69, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65,
	0x6d, 0x69, 0x78, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x65,
	0x6d, 0x69, 0x78, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x75, 0x62, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x0b,
	0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68,
	0x22, 0x53, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x69, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x72, 0x65, 0x6d, 0x69, 0x78, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x54, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x69, 0x78, 0x57, 0x6f,
	0x72, 0x6b, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x2e, 0x52, 0x65, 0x6d, 0x69,
	0x78, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xba, 0x01, 0x0a, 0x1b,
	0x52, 0x65, 0x6d, 0x69, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3c, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x72, 0x65, 0x6d, 0x69, 0x78, 0x2e, 0x52, 0x65, 0x6d, 0x69,
	0x78, 0x57, 0x6f, 0x72, 0x6b, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x1a, 0x43, 0x0a, 0x05, 0x57, 0x6f, 0x72, 0x6b, 0x73, 0x12, 0x24, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x65, 0x6d,
	0x69, 0x78, 0x2e, 0x52, 0x65, 0x6d, 0x69, 0x78, 0x57, 0x6f, 0x72, 0x6b, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_remix_remix_work_proto_rawDescOnce sync.Once
	file_remix_remix_work_proto_rawDescData = file_remix_remix_work_proto_rawDesc
)

func file_remix_remix_work_proto_rawDescGZIP() []byte {
	file_remix_remix_work_proto_rawDescOnce.Do(func() {
		file_remix_remix_work_proto_rawDescData = protoimpl.X.CompressGZIP(file_remix_remix_work_proto_rawDescData)
	})
	return file_remix_remix_work_proto_rawDescData
}

var file_remix_remix_work_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_remix_remix_work_proto_goTypes = []interface{}{
	(*RemixWork)(nil),                         // 0: remix.RemixWork
	(*DoRemixWorkPost)(nil),                   // 1: remix.DoRemixWorkPost
	(*RemixWorkPaginationPost)(nil),           // 2: remix.RemixWorkPaginationPost
	(*CreateRemixWorkPost)(nil),               // 3: remix.CreateRemixWorkPost
	(*UpdateRemixWorkPost)(nil),               // 4: remix.UpdateRemixWorkPost
	(*RemixWorkResponse)(nil),                 // 5: remix.RemixWorkResponse
	(*RemixWorksResponse)(nil),                // 6: remix.RemixWorksResponse
	(*RemixWorkPaginationResponse)(nil),       // 7: remix.RemixWorkPaginationResponse
	(*RemixWorkPaginationResponse_Works)(nil), // 8: remix.RemixWorkPaginationResponse.Works
	(*RelationRemix)(nil),                     // 9: remix.RelationRemix
}
var file_remix_remix_work_proto_depIdxs = []int32{
	9, // 0: remix.RemixWork.remix_info:type_name -> remix.RelationRemix
	0, // 1: remix.RemixWorkResponse.data:type_name -> remix.RemixWork
	0, // 2: remix.RemixWorksResponse.data:type_name -> remix.RemixWork
	8, // 3: remix.RemixWorkPaginationResponse.data:type_name -> remix.RemixWorkPaginationResponse.Works
	0, // 4: remix.RemixWorkPaginationResponse.Works.list:type_name -> remix.RemixWork
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_remix_remix_work_proto_init() }
func file_remix_remix_work_proto_init() {
	if File_remix_remix_work_proto != nil {
		return
	}
	file_remix_remix_relation_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_remix_remix_work_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemixWork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remix_remix_work_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoRemixWorkPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remix_remix_work_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemixWorkPaginationPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remix_remix_work_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRemixWorkPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remix_remix_work_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateRemixWorkPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remix_remix_work_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemixWorkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remix_remix_work_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemixWorksResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remix_remix_work_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemixWorkPaginationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_remix_remix_work_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemixWorkPaginationResponse_Works); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_remix_remix_work_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remix_remix_work_proto_goTypes,
		DependencyIndexes: file_remix_remix_work_proto_depIdxs,
		MessageInfos:      file_remix_remix_work_proto_msgTypes,
	}.Build()
	File_remix_remix_work_proto = out.File
	file_remix_remix_work_proto_rawDesc = nil
	file_remix_remix_work_proto_goTypes = nil
	file_remix_remix_work_proto_depIdxs = nil
}
